---
# This playbook contains plays that will be run on DB nodes.

- name: Install MariaDB package
  yum: name=centreon-database state=installed

- name: Start MariaDB Service
  service: name=mariadb state=started enabled=yes
